#There are certain sequences we know from Ryan's experimental data are
#tight binders; we will score these using our models to test how well
#the models work. The known tight binders are generated by this function.
#This is the WT sequence.
aa_template = 'EYVVEKVLDRRVVKGKVEYLLKWKGFSDEDNTWEPEENLDCPDLIAEFLQSQKT'
def generate_known_tight_binders():
    known_tight_binder1 = list(aa_template)
    #The first two known tight binders are from Ryan's previous publication.
    known_tight_binder1[2] = 'E'
    known_tight_binder1[5] = 'S'
    known_tight_binder1[39] = 'F'
    known_tight_binder1[40] = 'C'
    known_tight_binder1[42] = 'D'
    known_tight_binder1 = ''.join([known_tight_binder1[i] for i in [0,2,5,29,36,37,
                                            39,40,42]])
    known_tight_binder2 = list(aa_template)
    known_tight_binder2[2] = 'E'
    known_tight_binder2[5] = 'E'
    known_tight_binder2[39] = 'S'
    known_tight_binder2[40] = 'C'
    known_tight_binder2[42] = 'D'
    known_tight_binder2 = ''.join([known_tight_binder2[i] for i in [0,2,5,29,36,37,
                                            39,40,42]])

    #The next group is known tight binders generated in the current
    #experiment
    known_tight_binder3 = list(aa_template)
    known_tight_binder3[0] = 'W'
    known_tight_binder3[2] = 'E'
    known_tight_binder3[5] = 'E'
    known_tight_binder3[36] = 'Q'
    known_tight_binder3[39] = 'S'
    known_tight_binder3 = ''.join([known_tight_binder3[i] for i in [0,2,5,29,36,37,
                                            39,40,42]])
    known_tight_binder4 = list(aa_template)
    known_tight_binder4[2] = 'E'
    known_tight_binder4[5] = 'E'
    known_tight_binder4[29] = 'E'
    known_tight_binder4[36] = 'A'
    known_tight_binder4[39] = 'S'
    known_tight_binder4 = ''.join([known_tight_binder4[i] for i in [0,2,5,29,36,37,
                                            39,40,42]])
    known_tight_binder5 = list(aa_template)
    known_tight_binder5[2] = 'E'
    known_tight_binder5[5] = 'E'
    known_tight_binder5[36] = 'A'
    known_tight_binder5[39] = 'S'
    known_tight_binder5 = ''.join([known_tight_binder5[i] for i in [0,2,5,29,36,37,
                                            39,40,42]])

    known_tight_binder6 = list(aa_template)
    known_tight_binder6[2] = 'E'
    known_tight_binder6[5] = 'E'
    known_tight_binder6[29] = 'E'
    known_tight_binder6[36] = 'S'
    known_tight_binder6[39] = 'S'
    known_tight_binder6 = ''.join([known_tight_binder6[i] for i in [0,2,5,29,36,37,
                                            39,40,42]])
    known_tight_binder7 = list(aa_template)
    known_tight_binder7[0] = 'W'
    known_tight_binder7[2] = 'E'
    known_tight_binder7[5] = 'E'
    known_tight_binder7[29] = 'E'
    known_tight_binder7[36] = 'S'
    known_tight_binder7[39] = 'S'
    known_tight_binder7 = ''.join([known_tight_binder7[i] for i in [0,2,5,29,36,37,
                                            39,40,42]])
    known_tight_binder8 = list(aa_template)
    known_tight_binder8[2] = 'E'
    known_tight_binder8[5] = 'E'
    known_tight_binder8[36] = 'S'
    known_tight_binder8[37] = 'Y'
    known_tight_binder8[39] = 'S'
    known_tight_binder8 = ''.join([known_tight_binder8[i] for i in [0,2,5,29,36,37,
                                            39,40,42]])
    return [known_tight_binder1, known_tight_binder2,
                      known_tight_binder3, known_tight_binder4,
                      known_tight_binder5, known_tight_binder6,
                      known_tight_binder7, known_tight_binder8]
